version: '3.8'
services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "5000:5000"
    restart: unless-stopped
    volumes:
      - backend-data:/app
    mem_limit: 16g
    cpus: 4.0


  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    restart: unless-stopped
    volumes:
      - ./frontend:/app
    depends_on:
      - backend

volumes:
  backend-data: